const mongoose = require('mongoose');
const s = new mongoose.Schema({
  company_id:      { type: mongoose.Schema.Types.ObjectId, ref: 'Company', required: true },
  order_number:    { type: String, required: true },
  customer_id:     { type: mongoose.Schema.Types.ObjectId, ref: 'Customer' },
  customer_name:   String,
  customer_email:  String,
  customer_phone:  String,
  branch_id:       { type: mongoose.Schema.Types.ObjectId, ref: 'Branch' },
  warehouse_id:    { type: mongoose.Schema.Types.ObjectId, ref: 'Warehouse' },
  shipment_id:     { type: mongoose.Schema.Types.ObjectId, ref: 'Shipment' },
  status:          { type: String, enum: ['draft','confirmed','processing','allocated','partially_fulfilled','fulfilled','shipped','delivered','cancelled','returned'], default: 'draft' },
  priority:        { type: String, enum: ['low','medium','high','urgent'], default: 'medium' },
  items: [{
    sku:             String,
    product_name:    String,
    quantity:        { type: Number, default: 0 },
    fulfilled_qty:   { type: Number, default: 0 },
    unit_price:      { type: Number, default: 0 },
    discount_pct:    { type: Number, default: 0 },
    total_price:     { type: Number, default: 0 },
  }],
  subtotal:        { type: Number, default: 0 },
  discount_amount: { type: Number, default: 0 },
  tax_amount:      { type: Number, default: 0 },
  total_amount:    { type: Number, default: 0 },
  currency:        { type: String, default: 'KES' },
  payment_status:  { type: String, enum: ['unpaid','partial','paid'], default: 'unpaid' },
  paid_amount:     { type: Number, default: 0 },
  delivery_address: String,
  delivery_city:   String,
  requested_date:  Date,
  promised_date:   Date,
  delivered_date:  Date,
  created_by:      { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  notes:           String,
}, { timestamps: true });
s.index({ company_id: 1, order_number: 1 }, { unique: true });
module.exports = mongoose.model('SalesOrder', s);
